### ISSUE TITLE
Class 'dosamigos\selectize\Selectize' not found

### ISSUE THREAD

**Issue by salimkamboh** [2amigos/yii2-selectize-widget#14]
For last few days its showing error 
Class 'dosamigos\selectize\Selectize' not found.

It happened while I updated my local using 'composer update'. 
I was using "2amigos/yii2-selectize-widget": "*" in my require modules in composer.json

I have fixed it temporarily by using older version 0.1.1, But I request you to fix this issue ASAP as it does not let us use 1.0.0 or 1.0.1

Regards

**Comment by tonydspaniard** [comment]
@salimkamboh thank you for your comment. The problem was that we did a non-BC change and modified the libraries for a better approach: https://github.com/2amigos/yii2-selectize-widget/issues/11#issuecomment-83544994 

You can still use the old version if you feel more comfortable with, but in order to update to latest, you have to modify and use one of the classes provided. Thank you again.

**Comment by salimkamboh** [comment]
Thanks a lot for your response;
I have modified my code to use the latest version.
Regards
